{% set name = "stsynphot" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8d4e58ab3774154b2a4eebf08bfb3f04151e3900f75fdf2887bcf2008196337

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - numpy
    - extension-helpers
  run:
    - python
    - setuptools
    - beautifulsoup4
    - numpy
    - scipy
    - astropy
    - synphot

test:
  imports:
    - stsynphot

about:
  home: https://www.github.com/spacetelescope/stsynphot_refactor
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Synthetic photometry for HST/JWST
  description: |
    This is a replacement for IRAF STSDAS SYNPHOT and ASTROLIB PYSYNPHOT,
    utilizing Astropy and covering instrument specific portions of the
    old packages for HST (and soon JWST).
  doc_url: https://stsynphot.readthedocs.io/en/latest/
  dev_url: https://www.github.com/spacetelescope/stsynphot_refactor

extra:
  recipe-maintainers:
    - pllim
    - jhunkeler
    - rendinam
