{% set name = "stsynphot" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32bd5af99b149983be78483dfd9c202bf95a07124133899f9975ec191e7daa0b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - beautifulsoup4
    - numpy
    - scipy
    - astropy-base
    - synphot

test:
  imports:
    - stsynphot

about:
  home: https://www.github.com/spacetelescope/stsynphot_refactor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Synthetic photometry for HST/JWST
  description: |
    This is a replacement for IRAF STSDAS SYNPHOT and ASTROLIB PYSYNPHOT,
    utilizing Astropy and covering instrument specific portions of the
    old packages for HST (and soon JWST).
  doc_url: https://stsynphot.readthedocs.io/en/latest/
  dev_url: https://www.github.com/spacetelescope/stsynphot_refactor

extra:
  recipe-maintainers:
    - pllim
    - larrybradley
