{% set name = "stsynphot" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d8ccf36ee5479f25c36c32232d262a254e1c20886315a66987d29eadc6a672c

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - numpy
  run:
    - python
    - beautifulsoup4
    - numpy
    - scipy
    - astropy
    - synphot

test:
  imports:
    - stsynphot

about:
  home: https://www.github.com/spacetelescope/stsynphot_refactor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Synthetic photometry for HST/JWST
  description: |
    This is a replacement for IRAF STSDAS SYNPHOT and ASTROLIB PYSYNPHOT,
    utilizing Astropy and covering instrument specific portions of the
    old packages for HST (and soon JWST).
  doc_url: https://stsynphot.readthedocs.io/en/latest/
  dev_url: https://www.github.com/spacetelescope/stsynphot_refactor

extra:
  recipe-maintainers:
    - pllim
    - jhunkeler
    - rendinam
