travis:
  secure:
    BINSTAR_TOKEN: i9w/QyNo3Pk07BGjwK61NZtR62luZW0spGOStmXgxRLwHQqSPrmoOokSQAZpcuDWMGUFjNUYBhEVItA0xjyMn2kOP7LQNU3/aDm47ggNZnclKKAeoKrqTyha9tv6Sc5metrDzKOuainSrQApXARsmNBAocp0U+pE6f90qMl6wLVffm1gOwcLh4C73RjHQHvzipVo9Im1K0Io43YhYHAX0F2a6bonq4RT5Srun8Dmvpt5Xfh6jrOfPnlP1Ye18zmRHKXdrkvHgOzB/KwElQkfsWYJ8WI3vAP1zO82D29665+Nrcg6DQHeKZBVm1JNCsGiVB4d4d4D4hqXKiXJwy3cO6UldqZfsxWqqGmaTYUloBahlfG+aXMGUEfCe8+x80LpGj0dgrZ/b9/LALENMfLub4YgqzBXJTsbRog30fF8ktmuFiqnjAIZwUgSR/HO4/meufi+erAWpvUHQv4MGbpDqAv0hD8xcFm4C3BqATcrdRYd9ToRe7G1U8IA1j+9sTU+bWOKeeo04g15GvL/UfQqpdhq/eyyQMeUGuqmlJh6/wilHRhNGp8/xFjpHIZoLtt22Y1sR58smS+kEKDK/5f/vLYRlguSq9MbTyV2hG8pyqoQtF3yx347M0mqidHY/HnIapAn72j9U9jqqh8Xnx5kHJnaweMEOMhkE5ovwJ7mwms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
