travis:
  secure:
    BINSTAR_TOKEN: fhIyLl+3Tsr97SdhKf2RIgUbN9rVYicK/6+2dD05ueEtZ5mxgLzIe5r+i+Cm9v1bA0YmmkrJ1AEe+pRR1xJoMty6mBClUuqsjiaaan5I8sYcPdiLvQ5d5ovRXuhfr/XlQ/eKFjWOvH5qciuHhe4kY4H8IZU3W670M2a8g1batcFpL35pH+IAxmAiFw+dbdldO/7u1XpK44daqtOwvoRLJMgZc4TvnKP9dU2CuJ11oDfTWt671JygZlyWy2nREjlvfl1qASsV3Fta9IApV9QTlAY7I0c4cm9PhK1Vd4OVrNSimD0sY8RAnsr150PUeRQSFBjvD51QU8UKe+yWjE2Co9zrdW3N5lbiY8E8BV5ckcKuu1fy+RgbrrPOUYxU51chOoqiSa8GIC9pvaP8a5P806oTjG/NNSDmLxU0ZE5mtmNYdVAtk4NOxBwbgaQLoY8wl+E3uSiOkJMnpDp0XjpHv2P8uAjv4UyKutK/wJg+QEA+BXIr7uvfXiMXGduHiOTnbNFHqiT5pW5FovSz2AcoMRMits+BmApgBkdc1i/9/2l0iW2MYiOIX6l7kuWJCZZJxAIVoqTJyt1uqantvg1mVl5/g+vEMWce2MQo/66E5CdRy5OEmFcQLNE524E8C8A7LTORFcUtX2fLPDQ/8fMu2NtoGzCNZbFmdgfkLdGOPAs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
